### ISSUE TITLE
Notifications in PyCharm.

### ISSUE THREAD

**Issue by joe513** [python/python-dev-survey#2]
## Notifications in PyCharm.
Hey!

I don't remember there were any notifications about the survery in _PyCharm_. I think there would be more participants in the survery if **JetBrains** added notification in _PyCharm_ about the survery. I've randomly noticed this survery while was checking for Python docs. Most of Python programmers ussually don't go to Python site or very rarely do this.

I think survery findings will be more if **JetBrains** next time add notifications in _PyCharm_ about a survery. And it woul be nice if notifications were in "Tip of the day" daily window" or instead of upgrade notification in the right-bottom corner.

> If there were any notifications about the survery in PyCharm, I'm sorry about the post.

**Comment by gvanrossum** [comment]
That sounds like a terrible idea -- it would increase the bias towards PyCharm. Since the survey was apparently sponsored by JetBrains, and PyCharm came up as the most popular IDE, there have already been plenty of questions about the objectivity of the survey. As a matter of fact JetBrains says they did not promote the survey in any way. But if they had a notification about it in JetBrains they would not be able to say that, and the survey would be seen as a survey of PyCharm users (and why would the PSF sponsor that?) rather than a survey of *Python* users.

**Comment by joe513** [comment]
**@gvanrossum** Hey!  

I didn't know about  the bias towards PyCharm. I just thought that there would have been more participants if we used the most popular Python IDE to increase accuracy of findings. The number of participants is about 10_000, it seems like (_roughly speaking_) only Python newbies and docs-readers took part in the survey. I know you also mentioned about it in social networks, but it was not enough either.

If not PyCharm, maybe another popular IDE? Or tv advertising, outdoor advertising, newspaper advertising in the end?). I don't know, but I'm sure Python programmers are much more.

Anyway, thank you very much for your response, I really appreciate it.
